
const SUITS = ['ديناري','كؤوس','سيوف','عصي'];
function makeDeck(){const deck=[];for(const s of SUITS){for(let v=1;v<=7;v++){deck.push({suit:s,value:v,id:s+'-'+v});}}return shuffle(deck);}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a;}
function renderCard(c){const div=document.createElement('div');div.className='card';const v=document.createElement('div');v.className='val';v.textContent=c.value===1?'أص':c.value;const s=document.createElement('div');s.className='suit';s.textContent=c.suit;div.appendChild(v);div.appendChild(s);return div;}
class Game{constructor(playersCount){this.playersCount=playersCount;this.humanIndex=0;this.reset();}reset(){this.deck=makeDeck();this.table=[];this.hands=Array.from({length:this.playersCount},()=>[]);this.captures=Array.from({length:this.playersCount},()=>[]);this.scores=Array.from({length:this.playersCount},()=>0);this.current=0;this.lastCapturedBy=null;for(let i=0;i<4;i++){this.table.push(this.deck.shift());}for(let r=0;r<3;r++){for(let p=0;p<this.playersCount;p++){this.hands[p].push(this.deck.shift());}}updateUI();if(this.current!==this.humanIndex)this.aiTurnIfNeeded();}
findCaptures(card,table){const res=[];const n=table.length;function dfs(i,arr,sum){if(sum===card.value){res.push([...arr]);return;}if(sum>card.value||i>=n)return;dfs(i+1,arr.concat(table[i]),sum+table[i].value);dfs(i+1,arr,sum);}dfs(0,[],0);if(res.length===0){for(const t of table)if(t.value===card.value){res.push([t]);break;}}return res;}
playCard(player,card){const idx=this.hands[player].findIndex(c=>c.id===card.id);if(idx<0)return false;const options=this.findCaptures(card,this.table);let chosen=null;if(options.length>0){options.sort((a,b)=>b.length-a.length);chosen=options[0];for(const c of chosen){const tIdx=this.table.findIndex(x=>x.id===c.id);if(tIdx>=0)this.table.splice(tIdx,1);}this.captures[player].push(...chosen);this.captures[player].push(card);this.lastCapturedBy=player;if(this.table.length===0){this.scores[player]+=1;}}else{this.table.push(card);}this.hands[player].splice(idx,1);this.current=(this.current+1)%this.playersCount;if(this.hands.every(h=>h.length===0)){for(let r=0;r<3;r++){for(let p=0;p<this.playersCount;p++){if(this.deck.length>0)this.hands[p].push(this.deck.shift());}}if(this.deck.length===0&&this.hands.every(h=>h.length===0)){this.finalizeRound();}}updateUI();this.aiTurnIfNeeded();return true;}
aiTurnIfNeeded(){if(this.current===this.humanIndex)return;setTimeout(()=>{while(this.current!==this.humanIndex&&!this.isRoundFinished()){const ai=this.current;const chosen=this.aiChooseCard(ai);if(chosen)this.playCard(ai,chosen);else{this.current=(this.current+1)%this.playersCount;updateUI();}}},350);}
isRoundFinished(){return this.deck.length===0&&this.hands.every(h=>h.length===0);}
aiChooseCard(aiIndex){const hand=this.hands[aiIndex];if(hand.length===0)return null;const sorted=[...hand].sort((a,b)=>a.value-b.value);return sorted[0];}
finalizeRound(){if(this.table.length>0&&this.lastCapturedBy!==null){this.captures[this.lastCapturedBy].push(...this.table);this.table=[];}updateUI(true);setTimeout(()=>{this.reset();},1500);}}
let game=null;const tableCardsDiv=document.getElementById('tableCards');const playersContainer=document.getElementById('playersContainer');const statusText=document.getElementById('statusText');const scoresDiv=document.getElementById('scores');document.getElementById('newGame').addEventListener('click',()=>{const p=parseInt(document.getElementById('playersSelect').value,10);game=new Game(p);});document.getElementById('playersSelect').addEventListener('change',()=>{if(game){game=new Game(parseInt(document.getElementById('playersSelect').value,10));}});function updateUI(final=false){if(!game)return;tableCardsDiv.innerHTML='';for(const c of game.table){tableCardsDiv.appendChild(renderCard(c));}playersContainer.innerHTML='';for(let i=0;i<game.playersCount;i++){const pdiv=document.createElement('div');pdiv.className='player';const left=document.createElement('div');left.className='meta';const name=document.createElement('div');name.innerHTML=(i===0?'أنت':`AI ${i}`);const turn=document.createElement('div');turn.innerHTML=(game.current===i?'<span class="badge">دور</span>':'');left.appendChild(name);left.appendChild(turn);const right=document.createElement('div');right.className='hand';if(i===0){for(const c of game.hands[i]){const cd=renderCard(c);cd.style.cursor='pointer';cd.onclick=()=>{if(game.current===0){game.playCard(0,c);}};right.appendChild(cd);}}else{for(const c of game.hands[i]){const cd=document.createElement('div');cd.className='card';cd.style.opacity='0.7';cd.innerHTML=`<div class="val">${c.value===1?'أص':c.value}</div><div class="suit">${c.suit}</div>`;right.appendChild(cd);}}const cap=document.createElement('div');cap.style.minWidth='120px';cap.textContent=`مجموع مكاسب: ${game.captures[i].length}`;pdiv.appendChild(left);pdiv.appendChild(right);pdiv.appendChild(cap);playersContainer.appendChild(pdiv);}statusText.textContent=final?'نهاية الجولة — نقط محسوبة':`دور اللاعب: ${game.current===0?'أنت':'AI '+game.current}`;scoresDiv.textContent='النقاط: '+game.scores.map((s,i)=>`P${i}:${s}`).join('  |  ');}
